### ISSUE TITLE
[Question] Is this project still active?

### ISSUE THREAD

**Issue by LukeSavefrogs** [ThePoetCoder/safexl#1]
Hi @ThePoetCoder ,
I used your project and it really helped me... Thank you for the time spent creating this 🥇 

I wanted to know if you're still around to accept PRs (i would like to contribute to this project) and keep this great project alive 👍🏻 

I'll wait for your response.

**Comment by ThePoetCoder** [comment]
Hi Luca,
Thanks so much, I'm glad you like the project! I'm still here and the project is still alive. Updating the code here on GitHub is trivial, but publishing changes to PyPI will be a little harder, as I don't have that set up anymore. But I can figure it out again, what changes do you have in mind?
Thank you,
Eric
